USE SSAFY;
-- 7. id 2번과 4번 레코드의 나이를 15로 수정
UPDATE `MEMBER` SET AGE=15 WHERE MEMBER_ID IN (2,4);
SELECT * FROM `MEMBER`;

-- 8. 1번 레코드 삭제
DELETE FROM `MEMBER` WHERE MEMBER_ID = 1;
SELECT * FROM `MEMBER`;

-- 9. 레코드 추가(촉촉, 100)
INSERT INTO `MEMBER`(NAME, AGE) VALUES("촉촉",100);
SELECT * FROM `MEMBER`;
